### ISSUE TITLE
Error with CSV output. Dependencies?

### ISSUE THREAD

**Issue by bastorer** [pnsaevik/effluent#26] opened 2023-06-23 18:29 UTC
I tried running the example given at the top of the documentation page under usage
```
(base) [14:13:32:Effluent:Ben]$ cat config.toml
# Characteristics of the pipe and the effluent flow
[pipe]
time = [1970-01-01]
flow = [0.2]
dens = [1000]
diam = [0.5]
depth = [100]
decline = [0]

# Characteristics of the ambient water masses
[ambient]
time = [1970-01-01]
depth = [100]
coflow = [[0]]
crossflow = [[0]]
dens = [[1000]]

# Output options
[output]
csv.file = "out.csv"
csv.float_format = "%.6g"
trajectory.step = 5           # Time between trajectory points [s]
trajectory.stop = 30          # Time of final trajectory point [s]
release.start = 1970-01-01    # Time of first release [date]
release.stop = 1970-01-01     # Time of final release [date]
release.step = 3600           # Time between releases [s]
```

but got an error when it tried to write the output file
```
(base) [14:12:58:Effluent:Ben]$ python
Python 3.9.13 (main, Aug 25 2022, 18:29:29)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import effluent
>>> effluent.run('config.toml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Ben/.local/lib/python3.9/site-packages/effluent/script.py", line 15, in run
    model.run()
  File "/Users/Ben/.local/lib/python3.9/site-packages/effluent/model.py", line 45, in run
    for _ in self.irun():
  File "/Users/Ben/.local/lib/python3.9/site-packages/effluent/model.py", line 60, in irun
    self.output.write(time, result)
  File "/Users/Ben/.local/lib/python3.9/site-packages/effluent/io.py", line 263, in write
    df.to_csv(
TypeError: to_csv() got an unexpected keyword argument 'lineterminator'
>>>
```

I switched to running in an isolated conda environment, and that seemed to resolve the issue, which makes me think it's a dependencies problem. Could you provide a list of dependencies (or, perhaps most ideally, an `environment.yml` file that can be used to build a working conda environment)? The `environment.yml` that I used is
```
name: Effluent

dependencies:
 - python>=3.7
 - netCDF4>=1.4
 - matplotlib>=3.1
 - pip
 - pip:
   - effluent
```
but it would be good to have an official one / confirmation about dependencies :-)

There's also a warning about precision conversions, that I figured I'd mention. The warning message includes a suggestion on how to resolve it, which might be nice to avoid warning-spamming :-)
```
UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  return self._dset.isel(time=0)
```

[This is in reference to JOSS review https://github.com/openjournals/joss-reviews/issues/5554]

**Comment by bastorer** [comment] 2023-06-23 18:38
I'm also running into issues with netcdf outputs, but think that might also be a dependencies issue. None of the provided examples use netcdf output, so to make sure that I'm not just doing something silly with the config file, could you provide an example that gives netcdf outputs?

**Comment by pnsaevik** [comment] 2023-06-27 11:35
Are you on Windows or Unix? I could provide an `environment.yml` file, absolutely, with some helpful text in the documentation about conda usage. On Windows, netCDF is tricky without proper conda configuration, but the unix integration server seems to run without problems while only using pip.

**Comment by pnsaevik** [comment] 2023-06-27 11:47
Your specific CSV problem is related to an API change in `pandas 1.5.0`. I can tell pip to only use newer versions, but first I'll check if I can make it compatible with older pandas versions as well.

**Comment by pnsaevik** [comment] 2023-06-27 12:49
The nanosecond warning is silenced by #29

**Comment by pnsaevik** [comment] 2023-06-27 12:59
The csv problem should be resolved by #30. Can you confirm?

**Comment by bastorer** [comment] 2023-06-28 20:15
> Are you on Windows or Unix? 
Unix [more specifically Mac/OS X]

> I could provide an environment.yml file, absolutely, with some helpful text in the documentation about conda usage.
That would be great!

**Comment by bastorer** [comment] 2023-06-28 20:19
> The csv problem should be resolved by #30. Can you confirm?

Unfortunately, the problem seems to persist. I've uploaded the output of `pip install --verbose effluent` here 
[install.log](https://github.com/pnsaevik/effluent/files/11899646/install.log).

```
(base) [16:15:40:Effluent:Ben]$ python
Python 3.9.13 (main, Aug 25 2022, 18:29:29)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import effluent
>>> effluent.run('config.toml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Ben/opt/anaconda3/lib/python3.9/site-packages/effluent/script.py", line 15, in run
    model.run()
  File "/Users/Ben/opt/anaconda3/lib/python3.9/site-packages/effluent/model.py", line 45, in run
    for _ in self.irun():
  File "/Users/Ben/opt/anaconda3/lib/python3.9/site-packages/effluent/model.py", line 60, in irun
    self.output.write(time, result)
  File "/Users/Ben/opt/anaconda3/lib/python3.9/site-packages/effluent/io.py", line 263, in write
    df.to_csv(
TypeError: to_csv() got an unexpected keyword argument 'lineterminator'
```

**Comment by pnsaevik** [comment] 2023-06-29 20:30
I haven't yet created a new release number for the update, so it's still on 1.2. Which means you'll have to run pip uninstall effluent first, otherwise pip won't download the new version. And use pip git+https://github.com/pnsaevik/effluent to be sure to download the new version ("pip install effluent" installs from PyPI).

I'm travelling in June, but will return to this review in August. See you until then.

**Comment by bastorer** [comment] 2023-07-19 15:31
Sounds good, no worries. Give me a nudge when you're back and I'll give it another test :-)

**Comment by pnsaevik** [comment] 2023-08-04 10:18
I'm back now. Can you test whether the development version solves the csv issue? To install, do the following:
1. Uninstall effluent, `pip uninstall effluent`
2. Install the development version, `pip install git+https://github.com/pnsaevik/effluent`

**Comment by castelao** [comment] 2023-08-14 15:58
@pnsaevik , I started a new environment and re-installed the latest version of effluent. The tests pass and that example worked, but the nanoseconds warning is still complaining.

For reference:
effluent   097c01064

python                    3.11.4
pandas                    2.0.3

**Comment by pnsaevik** [comment] 2023-08-15 08:19
Strange, I cannot reproduce the warning, neither on windows or linux, nor on circle ci. I use the same python and pandas versions. Anyway, since it's just a warning, I suggest we close this issue now.

**Comment by castelao** [comment] 2023-08-16 10:48
@pnsaevik , since @bastorer raised this issue, it might be better to check with @bastorer before closing it.

**Comment by pnsaevik** [comment] 2023-08-16 10:53
Sorry, my bad!

**Comment by bastorer** [comment] 2023-08-28 18:55
Hey @pnsaevik , I'm happy to confirm that the test passed without errors or warnings on my end :-) 

Feel free to close the issue!

**Closed** 2023-08-30 05:05 UTC
